### ISSUE TITLE
Can't get `setCropGeometry` nor `setScale` to work

### ISSUE THREAD

**Issue by Kopert** [caprica/vlcj#1078]
- Java version: 16 (also tested with 11)
- JavaFX version: 16
- VLCJ version: 4.7.1
- VLC version: 3.0.16 (also tested with 3.0.11)

I'm trying to run this code (and some variations of it):
```
public void mediaPlayerReady(MediaPlayer mediaPlayer) {
    mediaPlayer.submit(() -> {
        mediaPlayer.audio().setMute(true);
        mediaPlayer.video().setSaturation(2.75f);
        mediaPlayer.video().setCropGeometry("120x120+10+10");
        mediaPlayer.video().setScale(2.0f);
        mediaPlayer.video().setAdjustVideo(false);
        mediaPlayer.video().setAdjustVideo(true);
    });
}
```

I tried running `setCropGeometry` and `setScale` separately, and I've also tried running it in different parts of the code - before starting a video, while it is running, etc. Neither command does anything at all.

I've also tried other arguments - `4:3` for the crop, `0.5f` for the scale, nothing happens. I'm interested in `setCropGeometry` specifically, but in my testing noticed that `setScale` also does nothing.

I also tried the [vlc-player](https://github.com/caprica/vlcj-player) project and, while it runs flawlessly, the crop commands *also* does nothing there.

I have used these same VLC installations/versions with C# bindings and both `cropGeometry` and `scale` worked on my small C# test, so I have to assume the problem is not with libVLC. I'm probably messing up my usage of VLCJ, any guidance is appreciated.

**Comment by caprica** [comment]
I was sure there was already an issue raised on this subject but I can't find it.

When using JavaFX, the video is being rendered into something like an ImageView (when using Swing instead it might be a BufferedImage and so on).

In these circumstances, VLC itself is NOT rendering your video, it is rendering full video frames to some buffer that you render yourself.

The native crop geometry and scale methods work on the native video for the case when VLC renders your video.

It does NOT work in the situation we're discussing here.

So if you want to crop the video, then you need to apply the crop effect when you render the ImageView (or whatever).

Same for scale, you set the scale on the graphics drawing context when rendering the video, using some sort of affine transform or whatever.

**Comment by caprica** [comment]
I found it: https://github.com/caprica/vlcj-javafx/issues/2

**Comment by Kopert** [comment]
Right, that makes sense.

Let me ask, before closing this issue, is there no other way in Java to render it more directly into the screen (so native crop would work)? And is there no way to render video that is more performant than `ImageViewVideoSurfaceFactory.videoSurfaceForImageView`? I was trying to build a video gallery and some videos have higher resolutions and end up chewing up the CPU.

I understand the limitations and expect the answer to be no, I'm just making sure I'm not missing anything.

**Comment by caprica** [comment]
The only way to get native video rendered directly into the screen is to use the normal "embedded" media player, not the direct media player. That is the best performance.

So that means you can't use JavaFX.

The JavaFX solution performs pretty well, in my experience. But it will consume CPU because it is basically software rendering each frame. With PixelBuffer it's as good as you can get.

However, I would say people seem obsessed with using like < 5% CPU. If your CPU load is under 100%, is there a problem, I don't really think so.

It is what it is, what's there already is likely to be the most optimised performant solution available - at least at the moment.

Nobody has ever suggested any improvement on what vlcj already provides here, but I'd be happy to hear about it.

With LibVLC 4.0.0 and vlcj-5.0.0, the OpenGL implementation should perform well, but it requires to to write an OpenGL application.

**Comment by Kopert** [comment]
I understand and agree with your assessment on CPU usage; it's just that, in some cases, CPU usage does hit 100% and frame drops start to happen. I'll take a look at the requirements and do some investigation in using the normal embedded media player with swing instead, see if it helps.

Anyway, thanks for your detailed answers and for the work on the project; VLCJ has served me very well on previous personal projects and it has helped me learn a great deal. Cheers 👍
