### ISSUE TITLE
Continuously increasing user objects / GDI objects in task manager when quickly playing/disconnecting video

### ISSUE THREAD

**Issue by gwdevelgit** [caprica/vlcj#1157]
Hi,

We are having a strange issue with switching between multiple live video feeds.  We have an application that has multiple panels/windows.  Only one panel is visible at a time and the user can switch between panels at will.  Some panels displays one live video feed from a camera.  If the user switches between panels quickly, then we observed using windows task manager, that the "User objects" / "GDI objects" climbs quickly.  The strange thing is that after the user does this maybe 10-20 times, then doesn't interact with the applicaiton anymore, the user objects still keep climbing.  You can watch them climb in task manager until the user objects reach 10000 and then trying to interact with the application again will result in a freeze/crash.  We have also seen the following exception when this happens:

```
java.lang.InternalError: The current process has used all of its system allowance of handles for Window Manager objects.
at sun.awt.windows.WToolkit.eventLoop(Native Method)
at sun.awt.windows.WToolkit.run(WToolkit.java:293)
[catch] at java.lang.Thread.run(Thread.java:662) 
```

We looked at our code and did lots of research online.  We found things to be aware of and avoid such as not calling back into the media player from the media player listener, but we already don't do this.  So this should be correct.

We tried performing the connect and disconnect code in new threads as per another article we came across, but this made no difference to the behaviour.

We profiled our application for memory leaks and we do not appear to be leaking any memory.

We also tried many different tools to try to get more information on what type of user/GDI objects are increasing such as the tools listed below, but none revealed any more information on the isssue:
    • process explorer
    • process monitor
    • task manager
    • winobj
    • profiler
    • gdiview

We enabled VLC logging as well but this didn't reveal any obvious issue.

The code we use to play the video:
```
if (networkCamera) {
  if (playImmediately) {
	 getMediaPlayer().media().play(mrl);
  } else {
	 getMediaPlayer().media().start(mrl);
  }
} else {
  String[] options = {":dshow-vdev=Integrated Camera", ":dshow-adev=  :live-caching=300"};
  if (playImmediately) {
	 getMediaPlayer().media().play(mrl, options);
  } else {
	 getMediaPlayer().media().start(mrl, options);
  }
}
```

the code we use to disconnect the video:
```
getMediaPlayer().controls().stop();
getMediaPlayer().release();
factory.release();
videoDevice.disconnect(VideoDevicePlayerImpl.this);
```

Note that we disconnect when the user switches back to a panel that was already initialized/playing a video before.  We track that we already connected to the video feed, so we disconnect first before we connect/play the media again.

Keep in mind that without changing the code at all, if we switch panels every few seconds instead of racing it, then the issue doesn't happen.

Do you have any suggestions as to what we can do to fix this issue?  Is this something we need to change in our code or is this a bug in vlcj?

Thanks

**Comment by caprica** [comment]
Very hard to say, especially when you post standalone snippets of code rather than a proper reproducible test case.

I can only speak generally, I would advise you don't destroy release media players, always keep them around and re-use them. Keep them in a pool or whatever.

I don't see where vlcj could be at fault here, vlcj essentially just passes your calls to LibVLC.

Maybe also keep in mind most of LibVLC is operating asynchronously, so if you execute a method like stop, it is not necessarily stopped by the time you call the next method.

**Comment by caprica** [comment]
There's a stopped event raised by the media player.

**Comment by caprica** [comment]
IIRC stop is actually synchronous with VLC 3.x, but that is gone with VLC 4.x and stop is now async.

**Comment by caprica** [comment]
I would address this first and redo your tests:

```
getMediaPlayer().release();
factory.release();
```

Don't release these resources, keep them in a pool. Use one factory for all your media players.

Dealing with native code is tricky, VLC uses many, many, third party libraries and any one of them could be implicated here. So I always recommend you keep your native resources around and reuse them rather than destroying them like you do here. Destroy them when your application exits.

And anyway what else can vlcj do here? You tell vlcj to release the media player, it calls libvlc_media_player_release(mp) and that's it. vlcj is not consuming your GDI resources, either the Java platform is or something in VLC or its plugins is.

**Comment by caprica** [comment]
Closing for now, if more information comes up that implicates vlcj it can be reopened.
