### ISSUE TITLE
what is a media-player-events thread??

### ISSUE THREAD

**Issue by HeeJoon-Kim** [caprica/vlcj#1188]
Hello!

I have a question about something strange while running vlcj in SpringBoot..

```log
MediaServerInstance [MediaServerInstance.java:103] - http-nio-8181-exec-1 channel_000163 - Media Changed!!  <-- first changed event.
....
MediaServerInstance [MediaServerInstance.java:103] - media-player-events channel_000163 - Media Changed!!  <-- next
....
MediaServerInstance [MediaServerInstance.java:103] - media-player-events channel_000163 - Media Changed!!  <-- next
```

First event run on "http-nio-8181-exec-1" thread, but next event run on "media-player-events"...
And the "media-player-events" thread keeps "running" without interruption. 
Also, when an event occurs, the "media-player-events" thread is incremented by one.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/20118729/230554771-1a87382e-e8c7-467a-8bba-6c6eebc699ac.png">

vlcj version is 4.8.2 and heare is a code..

```java
@Slf4j
@Data
@EqualsAndHashCode(callSuper = true)
public class MediaServerInstance extends MediaPlayerEventAdapter {
    // list player
    private final MediaListPlayer listPlayer;
    // media player of list player
    private final MediaPlayer player;

    private final MediaList mediaList;
    private final PlayerInfo info = new PlayerInfo();

    public MediaServerInstance(MediaListPlayer listPlayer, MediaPlayer mediaPlayer, MediaList mediaList, MediaServerPropertyChangeService propertyChangeService) {
        // media list
        this.mediaList = mediaList;
        // media player
        this.player = mediaPlayer;
        this.player.events().addMediaPlayerEventListener(this);
        // list player
        this.listPlayer = listPlayer;
        // set media player to list player
        this.listPlayer.mediaPlayer().setMediaPlayer(this.player);
    }

    @Override
    public void mediaChanged(MediaPlayer mediaPlayer, MediaRef media) {
        log.info("{} {} - Media Changed!!", Thread.currentThread().getName(), channelInfo.getChannelId());
        mediaPlayer.submit(() -> {
            List<String> playLists = listPlayer.list().media().mrls();
            Media m = media.duplicateMedia();

            // now play index
            info.setIndex(playLists.indexOf(m.info().mrl()));
            info.setMusicUrl(m.info().mrl());
            m.release();

            log.debug("{} {} - Play index: {}, url: {}", Thread.currentThread().getName(), channelInfo.getChannelId(), info.getIndex(), info.getMusicUrl());

            // record play info
            propertyChangeService.changeMusic(_this);
        });
    }
}
```

My question is.... How to handle events without the "media-player-events" thread being spawned?
Thanks..!!

**Comment by caprica** [comment]
This comes up from time to time.

Some related discussion in:
 - #52
 - #100 

Essentially, the threads are due to vlcj's use of JNA, and it is how JNA handles callback events (among other things I suppose) from native VLC code back into Java code.

This is why it is more apparent when you are using lots of events.

The "media-player-events" thread is the name vlcj tells JNA to use for these threads.

The last time I looked at this, I did a LOT of profiling and such, and the results are summarised in one or other of those related issues.

IIRC the basics of it is that just because you see so many Thread instances, it does not actually mean new threads are continually being created since JNA does some cleverness behind the scenes.

It has been a while since I last looked at this, but if someone can point to a specific problem with vlcj not using JNA correctly, I will take another look.

**Comment by caprica** [comment]
I suppose a follow-up is, despite the seemingly increasing instance counts, are you actually seeing real memory leaks after the GC has run?

**Comment by HeeJoon-Kim** [comment]
Thanks for quick answer!!

I'm not sure about memory leaks.. I will watch a few days and report it.~!!

**Comment by caprica** [comment]
Just a note for the future, this problem (if it is a problem) will eventually go away with JDK 21 (or maybe later)  when the FFM API is finalised since JNA will no longer be used.

**Comment by caprica** [comment]
A quick test with vlcj-5.0.0 (currently in development)...

I can't recall any significant differences around vlcj-4.8.x and vlcj-5.x.

No event listener:
![image](https://user-images.githubusercontent.com/1385879/230591817-1ea7f25b-5f76-411f-814e-cb459c090c48.png)

Event listener added for media changed events:
![image](https://user-images.githubusercontent.com/1385879/230592265-8193372b-ea6e-4e52-8823-366ee9ea5b33.png)

Looks to be working normally, the absolute number of threads is stable.

**Comment by caprica** [comment]
Using 4.8.2 and the same test, it was stable but with one seemingly "extra" media-player-events thread from time-to-time:

![image](https://user-images.githubusercontent.com/1385879/230593310-3d305c94-b553-4531-9c60-3ff62bb9aae9.png)

But it _was_ stable, it was not continually increasing.

**Comment by caprica** [comment]
btw, if you are going to duplicate the media ref, I think you should do it OUTSIDE of the submit call.

I also think your call to get the list from the player is potentially racy since you are putting it into a separate thread that will run some time later.

In fact, you should only use submit() if you are going to do something that interacts with the native media player, I am not sure you really need to use it given the code I can see above.

**Comment by caprica** [comment]
Closing due to lack of follow-up, if you have more details to add this can be re-opened.
