### ISSUE TITLE
How to release a list player instance.

### ISSUE THREAD

**Issue by HeeJoon-Kim** [caprica/vlcj#1194]
@caprica Hi. First.. thanks for kind reply.

I have a problem with jvm crash when release listPlayer instance.

```java
player.release(); // media player on listPlayer... crashed.. 
listPlayer.controls().stop(); // try to first stop and release.. but no lucky.. :(
listPlayer.release();
```

```log
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  uk.co.caprica.vlcj.binding.lib.LibVlc.libvlc_media_player_stop(Luk/co/caprica/vlcj/binding/internal/libvlc_media_player_t;)V+0
j  uk.co.caprica.vlcj.player.base.ControlsApi.stop()V+4
j  kr.co.aplayz.aplayz_streaming_server.server.MediaServerInstance.release()V+18
j  kr.co.aplayz.aplayz_streaming_server.server.media.service.impl.MediaServerServiceImpl.release(Lkr/co/aplayz/aplayz_streaming_se
rver/model/ChannelInfo;Ljava/lang/Boolean;)V+280
v  ~StubRoutines::call_stub
```

Hm... How to release listPlayer and attached mediaPlayer?

A crash is happened sometimes.. not always..

Thanks!!

**Comment by caprica** [comment]
Maybe don't release the player first. Release the player after you release the listPlayer.

I generally advise you keep these players around re-use them, rather than destroying them.

**Comment by HeeJoon-Kim** [comment]
Thanks for replay.

Following your advice, after disabling the list player, the crash is almost gone.

However, it still happens very occasionally. It would be nice to reuse the player, but since we spawn and play players in an unpredictable number, we need to release them.

thanks.

**Comment by caprica** [comment]
Why do you not just have a pool of players and reuse them? A pool should be fine because you know you can't for example run 100 media players concurrently, you will have some limit based on  your available resources.

Anyway, the problem here, in my experience of using and developing vlcj over the  years, is that the native code sometimes has problems when cleaning up instances. In a non-Java application, it might never be noticed, but a JVM will hard-crash on any such errors.

Literally when you call mediaPlayer.release() or mediaListPlayer.release(), the vlcj code is not doing much more than calling the underling native method method to free the instance, so it's not really pointing to a problem in the vlcj cleanup code, or at least I need to see some more evidence that it is.

One thing you could maybe try is making sure you stop the media player instances first - your code has a stop() call but it does not wait for the stopped event. So after you stop the instance, wait for the stopped event and then release the player instance. Doing this requires a bit more intricate code, unfortunately, but it might help.

**Comment by caprica** [comment]
I will also add, the upcoming VLC 4.x has changed the way players are stopped, and this might mitigate your issue, but that new version of VLC is still not near to release.

**Comment by HeeJoon-Kim** [comment]
Thank you very much. I'll seriously consider using a player pool.
And I'm looking forward to the new version. :)

**Comment by HeeJoon-Kim** [comment]
@caprica Hi. 
If I create a player in loop, how can I make it idle?
My question is if use a player pool, how to make idle stat..
A JVM crashed when called "stop()"..

Thanks!

**Comment by caprica** [comment]
You just stop the player.

If that caused a crash, something else may be going on. It's impossible to say without a repeatable test case. It can depend on how you're using threads, and as the number of concurrent media players you create goes up the more chance there is for a native crash I'm afraid.

If you're using Windows, there is a known issue with LibVLC/VLC 3.x that sometimes can cause a crash on stop.

If you want me honest opinion, LibVLC is best suited to being a single-instance media player. Problems like you're encountering can sadly occur when people try and push the boundaries of what LibVLC can reliably do.

I can reiterate a point I made before, with the upcoming LibVLC 4.x, they have changed the way stopping media players works, and it seems to be generally more reliable.

**Comment by HeeJoon-Kim** [comment]
Ok!

But.. I'm still confused.. Is "stop()" method  "listPlayer" or "listPlayer's mediaPlayer".. 

I am ALWAYS grateful for you.. :)
