### ISSUE TITLE
strange blue filter on vlcj5

### ISSUE THREAD

**Issue by diousk** [caprica/vlcj#1235]
Hi, 

I'm developing a compose desktop app.

When I use the current stable version uk.co.caprica:vlcj:4.8.2 to player a large video file (1GB), the video is a little laggy (behind audio about 2-3 seconds).

So I decide to explore the vlcj5 to seek for a better performance. (uk.co.caprica:vlcj-java8:5.0.0-SNAPSHOT)

The latest version of VLC 4.0(20240619-0414) is not working due to the NativeDiscover issues. 

I changed to download the earlier nightly built version of VLC [20240101-0411](https://artifacts.videolan.org/vlc/nightly-macos-arm64/20240101-0411/vlc-4.0.0-dev-arm64-bc0ae475.dmg) and the video start playing but there's a strange blue filter over the video.

<img width="933" alt="截圖 2024-06-19 下午2 57 04" src="https://github.com/caprica/vlcj/assets/2510682/afc300e9-f78d-4dbb-b5ed-fe56b8d4f95a">

the initialization of VideoPlayer in my Compose app is below
```
    val mediaPlayerFactory = remember { MediaPlayerFactory(PLAYER_ARGS) }
    val mediaPlayer = remember {
        mediaPlayerFactory
            .mediaPlayers()
            .newEmbeddedMediaPlayer()
    }
    val surface = remember {
        SkiaBitmapVideoSurface().also {
            mediaPlayer.videoSurface().set(it)
        }
    }
```

Can this issue be fixed? or is there a working version of VLC?

**Comment by caprica** [comment]
As VLC 4.x development was ongoing, there were some new problems relating to the buffer format (i.e. colour format) used by the video callbacks.

vlcj has always used the RV32 buffer format for this, but at some point in time, it seems the colour channel ordering changed.

So after some investigation, the colour format used by vlcj was changed to no longer use RV32.

At the time, this is where the issue was left.

If you are sure you are using both latest vlcj and latest VLC code, then it seems as though VLC may now have progressed to "fix" this colour format back to how it was previously and if so, I will need to go back and look at these changes in the vlcj-5 code.

**Comment by caprica** [comment]
And what native discovery issues are you having with latest?

**Comment by caprica** [comment]
You are not using latest vlcj-5.x then, libvlc_add_intf was removed some time ago.

You are always better off using vlcj-5.x from git, because I don't regularly push new snapshot releases each time something is changed.

btw, latest VLC source code does not build for me, so until that is resolved I can't check anything else.

**Comment by caprica** [comment]
I meant the opposite of that in fact.

I am recommending you clone the vlcj-natives and vlcj git repos, then build them on your local PC with maven.

I do not remember how recent the vlcj snapshot releases in the public Maven repos are, but I do not routinely update snapshot releases so they may be quite old, and especially so for the java8 artefacts - they are tedious to maintain.

I will try and fine some time to push new snapshot releases, but I can't promise when.

And if you do need to use a git repo as a maven repo, then I'm sure there is some official GitHub or Gradle documentation that could explain that for you.

**Comment by caprica** [comment]
I just now pushed latest vlcj-5 snapshot of vlcj-natives, vlcj (core) and vlcj-javafx, including the java8 branches, to the Maven shapshot repos.

I also made a small change to the vlcj-javafx-demo project (this does not get pushed to the snapshot repos).

I tested the vlcj-javafx-demo application with the latest VLC 4.x built today, no native discovery errors, and the colour format was also correct.

**Comment by caprica** [comment]
The other thing I'll mention, the video surface you use with Compose I think is not part of vlcj itself, so you may need to tweak something there.

It will be the similar to the JavaFX video surface, that's why I mentioned it above, but I do not control that code.

**Comment by caprica** [comment]
I don't think there's anything to do here, the issue can be reopened if there's still a problem with the latest versions of things.
