### ISSUE TITLE
How to use vlcj 5.0?

### ISSUE THREAD

**Issue by Him188** [caprica/vlcj#1240]
Hi, I would like to try vlcj 5.0 versions for #1232 on macOS, and maybe also try it on Windows ARM platforms.

I've search for GitHub README, https://mvnrepository.com/, and vlcj website, but failed to find how to add a dependency on vlcj 5.0. Sorry if I missed any documentations, but could you please help explain how to do this?

Also have you considered start releasing pre-release versions, e.g. `5.0.0-alpha01`? Because with `5.0.0-SNAPSHOT` the consumers will be forced to automatically update to the latest version, which might break functionality unintentionally (and which is a blocker for me to use vlcj 5.0 in my project as it's too risky).

Thanks a lot.

**Comment by caprica** [comment]
Snapshot releases of vlcj 5.0.0 are published to the standard Maven snapshot repository, you can read the Maven docs to find the small piece of boilerplate you need to enable the snapshort repo (or Gradle if you use that).

They are also pushed to the GitHub snapshot repository, again, check the GitHub documentation for how to enable adding GitHub projects as Maven repositories.

The real problem with vlcj 5.x and sticking with snapshots for the time being, is that it is not always easy to make sure it is in sync and working with the latest VLC 4.x (which is also pre-release). So really the only sensible option is to make sure you always have "latest" of both vlcj 5.x and VLC 4.x.

If I made, for example, a 5.0.0-alpha01 release, then I guess for you to no longer have a blocker with vlcj 5.x, it would mean pinning that version of vlcj to a specific pre-release build of VLC. I can foresee that getting quite messy.

Having said that, I will consider making a milestone release at some point. It has been like 4 or more years I think since VLC 4.x development was started.

**Comment by Him188** [comment]
Thanks for the replies!

> I guess for you to no longer have a blocker with vlcj 5.x, it would mean pinning that version of vlcj to a specific pre-release build of VLC

Yes, a versioned release would result in stable builds, such that once they are tested, they can be shipped to users. 

We have to pin both vlcj and VLC versions anyway. Unstable versions can not be used as it will break itself at anytime. 
For apps we bundle VLC into the app so the versions are always fixed. You have to do this even with vlcj 4.x, if I rememebr correctly from our previous conversations.

**Comment by caprica** [comment]
Yes, but relying on any particular nightly build of the pre-release VLC 4.x is going to be inherently risky. That's probably your biggest problem. vlcj-5.x is very stable really.

**Comment by Him188** [comment]
Indeed. I wanted to try VLC 4.x because VLC 3.x does not render any subtitle on macOS M-chips (see #1232). Since it's already not working, there's nothing to worry about the new version not working... And we can always rollback to the current version if the upgrade causes any regression during the app's alpha releases. 

Looking forward to vlcj 5 versioned pre-releases. Would definitely give it a try on these platforms that are already broken.

**Comment by caprica** [comment]
vlcj-5.0.0-M1 milestone release pushed to Maven Central repository.

It usually takes maximum 4 hours or so to propagate.

**Comment by Him188** [comment]
@caprica Thanks!
