### ISSUE TITLE
How can we integrate vlcj in android  

### ISSUE THREAD

**Issue by nazarhussain** [caprica/vlcj#216]
Hi, 

I have two questions related to VLCJ. 
1. How can we integrate VLCJ in Java. (I tried to search for it but can't find any clear directions)
2. Can we play DVD Title (VIDEO_TS.INFO) that actually shows the video titles and give option to choose which one needed to play. 

Give me some directions towards these questions. 

Thanks In advance.

**Comment by WeMediaAnime** [comment]
Hi, I have a suggestion that could significantly increase the popularity and use of the vlcj library. Since Kotlin is fully interoperable with Java, I believe that extending vlcj to support Kotlin Multiplatform (KMP) would be a great addition. This would allow developers to work with vlcj in a single project, whether it's an Android app, desktop application, or even a web or iOS app, all within the same codebase. Currently, working with JavaCV and FFmpeg can be quite cumbersome, and this could be a much smoother approach for Kotlin developers. Kotlin's ability to work across multiple platforms makes this a perfect opportunity to improve the versatility and accessibility of vlcj, which would attract more developers, especially since Kotlin integrates seamlessly with Java. This addition could have a significant impact on the community and broaden the reach of the library.

Thank you for considering this!

**Comment by caprica** [comment]
I doubt the viability of this suggestion tbh.

- There are issues with vlcj on Android, as described here in fact. Some aspects of this may be better when vlcj removes JNA completely, but other issues remain.
- I have no idea about KMP or what difficulties there would be bringing LibVLC into that world.
- There is also a libvlcjni project that integrates VLC at a deep platform level.
- A few people posting on a GitHub issue does not demonstrate any real demand.

Having said that, if a corporate sponsor would like to offer to fund such work, then sure, I'd consider it.
