### ISSUE TITLE
fatal error at libvlccore.dll

### ISSUE THREAD

**Issue by szepc8** [caprica/vlcj#309]
![fatalerror](https://cloud.githubusercontent.com/assets/2802503/5957509/22d681d4-a7c3-11e4-9556-090832ea8faf.png)
Test it on : 
          -  Intel(R)Core2CPU E8400@3GHz;4GB RAM(2,97 verwendbar );32bit-windows7 
Test case:
       - Open new instance of the player(main player) in  full screen mode and play some video's - the player works
       - Set the main player to pause mode 
       - Open new instance of the player (event player) and play some videos - the player works 
       - After a few seconds fatal error appears : see picture from above

Other details:
     -  in the same circumstances if I use pictures instead of video, works fine
     -  on new computers generation as: core i3,core i5 or core i7 works fine as well 
     - it works also on: 
              Inter(R) Core2CPU 6300 @1.86GHz;4GBRAM(3.12GB verwendbar);32bit-windows7
     -  I would like to mention that is no hs_error message and the VLCJ logging system is clean

Could be hardware incompatibility ?

**Comment by caprica** [comment]
Insufficient information to make any reasonable conclusion, frankly.

**Comment by caprica** [comment]
If it works on one PC, but not another, then it's likely the graphics driver, or as I think you are using two separate video players it may be the case that the GPU does not have sufficient resources on one of the PC's to support multiple video players.

On top of that, LibVLC/vlcj has well known issues with multiple "in-process" video players having the potential to cause fatal crashes because one or more of the native libraries that LibVLC uses is not thread-safe and/or not re-entrant. There's nothing can be done about that in vlcj, apart from having your application take care with how to use multiple media players.

One mitigation strategy is to make sure you prepareMedia() and startMedia() in sequence for each media player rather than playMedia() concurrently for each media player.

This issue can be re-opened if you provide more information, or a simple test-case that demonstrates the problem. Otherwise there's nothing more I can really add.
