### ISSUE TITLE
Logging to different log output than stdout

### ISSUE THREAD

**Issue by masterX244** [caprica/vlcj#316]
Is there any chance that the logger you provided allows the change to a different output stream than the System.out one? Currently you can't use a different logging framework without catching all stdout/stderr output

**Comment by caprica** [comment]
First some background... the reason for using a homebrew logging framework rather than using anything else was because vlcj has very limited dependencies, in fact it only depends on JNA and the JNA Platform jars.

So bundling in SLF4J, or (gasp! commons-logging) was seen as overkill.

These days, I am no longer entirely convinced about that argument and would seriously consider adding SLF4J in place of the homebrew logging.

But changing that touches just about every artefact in vlcj.

In the immediate term, I can probably provide a method to set the streams to use for the log rather than using System.out/System.err if that is what you're asking.

**Comment by caprica** [comment]
See if b3b2b9df426c5b5cca66131716ee1fea8a7fcfd1 gives you what you need, at least in the short term.

Longer term I am considering using SLJ4J instead.

**Comment by masterX244** [comment]
simplest solution would have been to allow to set a non-default printstream so you could have used for example Log4js feature to output any printstream to the logfile or you could hae written a printstream that redirects the output to any logger

**Comment by caprica** [comment]
I don't really understand the comment to be honest.

It seemed simplest to me to allow the vlcj application to set it's own output stream. I don't see how it gets simpler than that.

Maybe if you explain your idea a bit more I can reconsider.

**Comment by masterX244** [comment]
updated my comment before, had answered too fast. you got exactly what i meant as the short-term solution since with the way to add the custom Printwriter supplying a adapter is easy

**Comment by caprica** [comment]
OK thanks!
