### ISSUE TITLE
Any hints on getting "Output/Written/Sent" statistics working?

### ISSUE THREAD

**Issue by dhirwin** [caprica/vlcj#417]
All,

This isn't really an issue with VLCj, but just want to see whether there are any suggestions / hints on getting the "Output/Written/Sent" statistics working. They don't seem to work in VLC (2.1.5 or 2.2.1 on CentOS or in Windows7) so they very likely shouldn't work in VLCj either. But I'm using VLC / VLCj as a sort of transcoding server and occasionally the output stream just stops with no noticeable errors in the logs. I thought I could use the output stream statistics as a way to potentially trap these situations. Right now the only statistics that seem to update are the "Demuxed data size" and "Content bitrate". 

Thanks again in advance,
Dave

**Comment by caprica** [comment]
Unfortunately I can only suggest adding debug output to VLC and building it yourself to see if it helps.

I do recall seeing all those statistics updating in my own apps, but this was quite a while ago - I don't normally need those stats.

**Comment by dhirwin** [comment]
Thanks for the feedback.

If I'm trying to capture a situation where VLC suddenly stops decoding video yet the incoming stream is still available, do you know if there are any available VLC events that I might use to capture this?

**Comment by caprica** [comment]
There aren't any. All you get from LibVLC is error or finished, and you don't get any notification when a stream disconnects.

What might be possible is to patch VLC to send an event when a stream disconnects. But that's likely not easy.

I understand the frustration, but in my experience LibVLC is more suited for embedding a media player in an application (and ideally only one instance of a media player), rather than using it in some sort of server app - you really push it to the limits of what is possible if you do that.

**Comment by caprica** [comment]
Also, IIRC, different media types update different statistics. So e.g. a local MP4 file might update everything, but a stream might only update a sub-set.
