### ISSUE TITLE
Feature request: JavaFX 8 view

### ISSUE THREAD

**Issue by joeyroosing** [caprica/vlcj#422]
Is it possible to add a view to be used in JavaFX similar to the existing MediaView class:
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/media/MediaView.html

I could also try it myself, but then ill need some pointer on how the swing version is implemented as reference. I could not directly find it in code. 

Reason I would like the reference is so I can stick to the same coding standards and make it behave similar.

**Comment by caprica** [comment]
I don't understand the scope of the request.

Have you seen the vlcj-javafx project? What else are you asking for?

Having vlcj play directly into a JavaFX view without using direct rendering
like the vlcj-javafx project already does is impossible as far as I know at
the moment.

**Comment by joeyroosing** [comment]
I apologise. I failed to see the mentioned project. I will look into that one. Thanks for the headsup.

**Comment by caprica** [comment]
For Swing, there is no particular code as such since the video is rendered directly by VLC into an AWT Panel.

For JavaFX, this simply does not work.

VLC needs a heavyweight component to render video into, and JavaFX does not support adding an AWT Panel to a Scene and having the video render properly. There isn't anything that can be done about that really.

So the alternative is to use the vlcj "direct rendering" approach, and that is what is used in the vlcj-javafx project.
