### ISSUE TITLE
Missing events and inconsistencies between VLC and libvlc

### ISSUE THREAD

**Issue by hjohn** [caprica/vlcj#450]
I'm wondering if you perhaps have an idea what might be causing the issues I'm seeing.

I have Windows 10, with VLC 2.2.1 64-bit, Java 8 64-bit, running VLCJ 3.5.0 (but also happened with 2.4.1).  CPU is a quad Xeon, DDR3 24 GB RAM.

I'm seeing the following.

1) Older MKV movies play fine.

2) Newer MKV's are slow to respond and are missing events (timeChanged event normally fires about 2-3 times per second -- with these movies that's the same, except they often contain gaps of upto 10 seconds with no events at all coming in).  During this time however the movie plays on flawlessly, no stutter in audio or video.. just the events.

The gaps are very consistent, that is, if there's a gap at the start of the movie, and at 13 seconds and 50 and 60 seconds, it will always show these gaps when played again...

3) There are big differences in what VLC itself does and what libvlc does -- I thought they should function similarly.  When I play a certain movie, VLC can take 10-15 seconds to even start playing, but with libvlc it plays within 5 seconds, although it is still showing the missing timeChanged event behaviour.

4) The newer MKV are slow when skipping (takes 5 seconds to get sync again, even with enable-fast-seek) -- the same files in VLC skip near instantly.

To try debug this I've tried so far:

1) Installing a new codec pack
2) Upgrading VLCJ (2.4.1 -> 3.5.0 -- tried 3.10.0 also, but it gives an error about plugins)
3) Copy movies locally (instead of from gigabit LAN)
4) Windows Media Player plays the movie with the slow startup time almost instantly

The same system under Windows 7 (with 32-bit versions of VLCJ 2.4.1 and an older VLC) did not show this behaviour -- I have this feeling I'm missing something obvious.

**Comment by caprica** [comment]
It's very difficult to say.

In essence, all vlcj does is call the native methods libvlc_media_new_path (or libvlc_media_new_location),  libvlc_media_player_set_media, and libvlc_media_player_play.

So vlcj can't seriously be implicated in any problem you're seeing here.

LibVLC does have a different code path when compared to the VLC application (since the VLC application does not itself use LibVLC) so that is an avenue for some differences in observed behaviour.

What you could make sure is that your VLC application does not have different settings from your LibVLC application - things like network caching can have an impact, so in the case of your 10-15 seconds VLC might be pre-buffering that. It's just a guess though.

The problem you refer to in 3.10.0 is related to #449.

**Comment by hjohn** [comment]
Ok, I'll see if I can track down the causes of the slow downs.  Thanks for taking a look.

**Comment by caprica** [comment]
Usual advice applies, enable the logs and compare the differences... sorry, but it's hard to be any more help with problems like this.
