### ISSUE TITLE
Bump JNA to latest version 4.5.x

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj#495]
Resolves issue with shared drives on the inferior OS.

See #493.

Need to remove the vlcj MONITORINFO class as part of this change.

**Comment by Abu-Abdullah** [comment]
any update on the release date of 3.11.0

the current jna 4.1.0 packaged today is not working with me (cannot discover the plugins folder). i need to replace it with jna 4.4.0 manually to work.

**Comment by caprica** [comment]
You confirmed for certain that it works with 4.4.0?

**Comment by Abu-Abdullah** [comment]
yes, i can confirm this.
at least on my setup:
- Windows 10 / 64 bit
- jre 64-Bit (1.8.0_152) with vlc 2.2.6 64bit

I'm using:
```
NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), programFolder+"bin/vlc");
Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
```

for some reason, it is working now with jre 32-bit with vlc 2.2.0 32-bit on windows 64bit. previously it was not working if I'm not mistaken.

another point, in jna 4.1.0 i need to set the VLC_PLUGIN_PATH, otherwise it will not work. it is been solved in 4.2.0 and above

**Comment by caprica** [comment]
Thanks for the feedback.

JNA and LibVLC has been a problem since after JNA 3.5.2, hopefully this makes it better.

I'll update vlcj, do some testing, and then maybe push a release out soon-ish.

**Comment by caprica** [comment]
Latest is currently 4.5.1, commited at 486b973037e6ab734d612c1f8def36999f89374c
