### ISSUE TITLE
PLease clarify VLCJ + plugins + auto discovery issue in 3.10.1

### ISSUE THREAD

**Issue by aklisanic** [caprica/vlcj#501]
Can anyone clarify this problem to me:

I downloaded VLCj source and JavaFX-VLCJ tests. Copied test classes into VLCJ project so they find all needed classes. I saw numerous posts stating that Tests are working but they do not. I definitely need to add these lines at the start of each test:

`        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "D:\\Work\\vlcj-master\\vlc-2.2.3");
        LibC.INSTANCE._putenv("VLC_PLUGIN_PATH=D:\\Work\\vlcj-master\\vlc-2.2.3");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
        LibXUtil.initialise();`

After this everything is fine. Can someone from support team confirm that this is OK and I am not missing something else (like correct way of configuring this)? I am asking this because in 3.10.1 release notes is stated that this problem is fixed but I still have it. My system is Win 8.1 + java 8.

I have both 32 and 64 bit versions installed for testing and when I point to them - everything is fine, just Native Discovery never finds them. Same is with plugins. I need to create ENV variable or to add that line of code.

**Comment by caprica** [comment]
You don't say precisely what your error is other than it doesn't work. Please be more clear.

In your case it looks like VLC is installed in a non-standard location, was your VLC installed using the Windows installer? If not, how do you epxect vlcj to know where to look?

**Comment by aklisanic** [comment]
It's installed using win installer (several times different versions). 

In my example I gave up with those installed versions and  used portable version.

Error is that installed VLC is not found. After I add 
`NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "D:\\Work\\vlcj-master\\vlc-2.2.3");`
It finds it but then complain abut plugins.
That is solved with:
`LibC.INSTANCE._putenv("VLC_PLUGIN_PATH=D:\\Work\\vlcj-master\\vlc-2.2.3");`

So, my question is how to make VLCJ actually finds installed VLC.

**Comment by caprica** [comment]
If you use a portable version of VLC, then you will have to explicitly set the path.

If you use a proper Windows installer, it creates a registry key with the install path. vlcj reads this registry key and sets the appropriate directory for JNA.

The problem with the plugins not being found is a big annoyance that was introduced in a change from JNA 3.5.2 to JNA 4.x. In short, the JNA implementation changed in a way that broke LibVLC's loading of plugins. This has caused no end of trouble for vlcj (and other LibVLC applications that use JNA), so much so that I am considering reverting the vlcj requirement for JNA back to 3.5.2, at least on Windows.

It would be nice if the automatic discovery could accommodate this, for sure.

**Comment by aklisanic** [comment]
OK, I just needed status update on this. Looks like JNA is causing my problems too. I am perfectly fine using portable version as long as it works. 

Thanks.

**Comment by caprica** [comment]
I would prefer a 100% robust solution, there is still an open vlcj issue on this subject so it might get addressed in a future version.

**Comment by aklisanic** [comment]
Good luck with that. In the meantime, I hope code snippet from my first post will help those with similar issues.
