### ISSUE TITLE
VLC.exe works but LibVLC through VLCJ has errors with plugins

### ISSUE THREAD

**Issue by ryantheseer** [caprica/vlcj#545]
I have installed a custom build of LibVLC on two different Windows 7 PCs. On one, everything seems to run fine. On the other, I run into two different scenarios:

1. When running VLC.exe, it finds 419 modules, including the Live555 module, which is of particular interest because I'm trying to stream a video from RTSP/RTCP/RTP. Video playing runs fine.

2. When running LibVLC.dll through VLCJ Java wrapper (on the same machine that works when run from VLC.exe), it finds 397 modules and it shows 15 of similar warnings:
`core libvlc warning: Cannot load module 'xyz.dll' (The specified module could not be found (error 126))`

And yet the files are all where they say they are supposed to be, and while running from VLC.exe, they are found and loaded successfully, as the case may be!

It is not a matter of VLCJ not finding the correct VLC installation folder, because if I delete one of these files that it cannot load, it no longer gives me an error for the deleted file.

I looked at one of the files in Dependency Walker, and I notice that most of the files that cannot be loaded depend on libgcc_s_seh-1.dll, a file that was produced by the Windows 64-bit build of VLC, although I notice that in the official release of Windows 64-bit VLC, this file does not exist, but it has an axvlc.dll and an npvlc.dll.

Are these clues enough to fix my problem?

**Comment by caprica** [comment]
Since it works on one of your environments but not the other, I highly doubt the problem is with vlcj - and by that I mean that it probably can't be solved by making any change in vlcj.

I can only recite the usual things that can sometimes be wrong with problems like this:

 - mismatched JVM/VLC architecture
 - jna.library.path
 - JNA Native.loadLibrary
 - VLC_PLUGIN_PATH
 - user account / other security issues

If you try the tutorial here, http://capricasoftware.co.uk/#/projects/vlcj/tutorial/first-steps, what happens?

Carefully check the environment (i.e. variables, paths and so on) in each of your PCs and look for differences.

Are you running with administrator privileges on one PC and not the other.

**Comment by caprica** [comment]
I wonder if this is related https://github.com/caprica/vlcj/issues/542

**Comment by caprica** [comment]
Since you cross-posted this to stackoverflow, I'll close it here.
