### ISSUE TITLE
How catch message errors like this?

### ISSUE THREAD

**Issue by Dizzman** [caprica/vlcj#550]
I very rarely getting some fatal error when my program not exit and not continue.

bellow to example

 execute command : java -jar mystreamer.java

all ok .. all warking long time
and this messages i can catch in my java program 
[access_output_http  ] (access out          ) WARNING: ":172.0.0.1" HTTP host might be ignored in 
[access_output_http  ] (access out          )  NOTICE: Consider passing --http-host=IP on the command 
[core                ] (access out          )   ERROR: Ignoring port 172 (using 8081)
[core                ] (access out          )  NOTICE: Specify port 172 separately with the http-port option 
[core                ] (access out          )   ERROR: socket bind error: Permission denied
[core                ] (access out          )   ERROR: socket bind error: Permission denied
[core                ] (access out          )   ERROR: cannot create socket(s) for HTTP host
[access_output_http  ] (access out          )   ERROR: cannot start HTTP server
[stream_out_standard ] (stream out          )   ERROR: no suitable sout access module for 
[core                ] (stream output       )   ERROR: stream chain failed for 

but this message i'cant to catch
### 2315 [main] DEBUG uk.co.caprica.vlcj.log.NativeLog  - release()
2315 [main] DEBUG uk.co.caprica.vlcj.log.NativeLog  - destroyInstance()
2315 [main] DEBUG uk.co.caprica.vlcj.log.NativeLog  - Shut down listeners...
2315 [main] DEBUG uk.co.caprica.vlcj.log.NativeLog  - Listeners shut down.

example 2
![default](https://cloud.githubusercontent.com/assets/25510074/24591887/a81f754e-1814-11e7-8cca-b49a71bee12c.png)

What i need to do for catch it?
I use **try catch** any where in code but it doesn't help my....

**Comment by caprica** [comment]
Well, try..catch is never going to work here because the messages you are asking about are coming from the native (LibVLC) code and they are not happening inside the JVM.

From the Java side the only thing you can do is listen for an "error" event in a media player event listener, but you will not no *why* it failed, or what the particular error was, it will just be a general failure.

You can try using the vlcj `NativeLog` class. This class provides a way to access the native log messages generated by LibVLC so in theory you can search that log (e.g. using pattern matching) to find these messages. But this is NOT recommended because those native log messages are not LibVLC API, they are simply debug messages that VLC's plugins are generating. With a new version of VLC those errors may be different or not appear at all.

The reason for the fatal JVM crash, I don't know, and you can never stop that happening by writing Java code.

The best thing you can do here is probably not to focus on these native log messages and instead focus on why your stream is not playing.

**Comment by Dizzman** [comment]
I used NativeLog like NativeLogTest.java in example.
Very rarely i got some errors when application can't exit and continue.
Well...i'll try cvlc

**Comment by caprica** [comment]
You can't write Java code to stop the JVM crashing.

The JVM is crashing because native code in LibVLC/VLC or one of it's plugins is crashing - or there is some other problem in your own application to do with your vlcj components being garbage collected when they shouldn't, that is really the only thing I can think of.

You can not write any Java code to stop the JVM crashing. It's as simple as that.
