### ISSUE TITLE
vlcj cannot handle error when lost connection to video source in preview mode

### ISSUE THREAD

**Issue by nhuythuy** [caprica/vlcj#551]
If we use an USB camera in preview mode as the sample code below, and we disconnect USB camera when it is previewing, then we cannot stop EmbeddedMediaPlayer object, this object is still libvlc_Playing (libvlc_state_t = libvlc_Playing) after we disconnect USB camera.

    public String[] buildPreviewOnly() {
        List<String> params = new ArrayList<String>();
        params.add(":no-video-title-show");
        params.add(String.format(":dshow-adev=%s", getAudioInDevice()));
        params.add(String.format(":dshow-vdev=%s", getDeviceName()));
        params.add(String.format(":dshow-aspect-ratio=%s", getAspectRatio()));
        params.add(String.format(":dshow-size=%dx%d", width, height));
        params.add(String.format(":sout-display-video :sout=#transcode{fps=%d}:duplicate{dst=display{noaudio}}", getFramerate()));
        String[] result = params.toArray(new String[params.size()]);
        logger.log(Level.INFO, Arrays.toString(result));
        return result;
    }

**Comment by caprica** [comment]
The native media player is still in the playing state, vlcj's EmbeddedMediaPlayer reflects the state of the native media player.

Frankly, I don't think VLC is all that good at handling things like disconnecting USB devices. Or maybe it's still "playing" because it expects the device to be reconnected and it can continue. I don't know.

Unless you received an "error" callback on the media player event listener, I don't think there's anything you can do.
