### ISSUE TITLE
Videofilter

### ISSUE THREAD

**Issue by MS-Tech** [caprica/vlcj#575]
Hello,

in VLC i can set a ImageWallFilter. With this filter i can divide a video in several pieces. Can I set the filter over vlcj and play the pieces in different views?

Greetings
MS-Tech

**Comment by caprica** [comment]
That filter has no support in the LibVLC API.

The only thing you can do is try and set the filter options (command-line switches) as options when you create a MediaPlayerFactory.

The problem is that that filter will create more than one native video window, there is NO way to embed those native windows in a Java application.
