### ISSUE TITLE
VOD Player without abort after 10s.

### ISSUE THREAD

**Issue by Jahyrm** [caprica/vlcj#580]
I'm trying to make a VOD app.

I have used the VodTest.java example in this git, for my server. I've just renamed the video files I'm using. I think everything is fine with the VodServer.

But when I run a client with a simple vlcj player with this argument rml: rtsp://@127.0.0.1:5004/Movie1

Sometimes the video is displayed, but other times I get this error in the console:
`[000000001aaa8270] Live555 demultiplexing error: no data was received in 10s, aborting`
OR
`[000000001aaa2a90] live555 demux error: no data received in 10s, aborting`

I guess something is wrong with the connection, is there any way to not abort the execution, and wait for more than 10s?

**Comment by caprica** [comment]
The VOD part of the API is very much unused as far as I know so it's difficult to get a grip on what might be wrong.

All I can say is the messages you've posted come from VLC itself (actually its plugins).

All you can do through the LibVLC/vlcj API is hope that you get an error event being raised, otherwise you can't trap the error. There is nothing in the API to control connection timeouts, you *might* find something in a command-line switch to help, in which case you'd pass that command-line switch as a media player factory argument, or as a "media option" when you play/queue the media.
