### ISSUE TITLE
EmbeddedMediaPlayerComponent whitout aspect ratio

### ISSUE THREAD

**Issue by cassiohoffmann** [caprica/vlcj#590]
Hello friends! Congratulations on the incredible Vlcj!

I have an application made in JavaFx for video playback.
What I have realized is that the natural resources in creating an acceptable performance in old machines or with features for video playback.

as I saw that there is this wonderful port of vlc for java, I tried using a lot of javafx but it still was not acceptable in the process of storing images
to view is still slow.

Well, alternatively do a test application with swing + vlcj. Here are the results:

- if I use factory.newDirectMediaPlayer using callback to display as images on my canvas, the performance is not satisfactory, there are a lot of sliders
and gagging without video

- if I use an EmbeddedMediaPlayerComponent I have exceptional performance. But I do appreciate the aspect format that I can not change because I need
than a full image on a screen and ignore the aspect ratio

Could you give me a hand? as I use EmbeddedMediaPlayerComponent without needing to use an aspect ratio. Easier power to make a screen that is video miss
as original proportions but with the excellent performance shown by the EmbeddedMediaPlayerComponent.

I believe many people without the same doubt.

I await your return !!

**Comment by APayerl** [comment]
First I think this is more suited on stackoverflow.com.
I have no idea what type of performance you need but if you check out this demo application I've made with the DirectMediaPlayer you might get some ideas!
https://github.com/APayerl/VlcjWindDemo
That Demo project is using my wrapper for Vlcj though. Available if your interested here.
https://github.com/APayerl/VlcjWind

**Comment by caprica** [comment]
Sorry this is not clear to me what you want, can you reduce your issue down to a specific question?

Having said that...

You can set the aspect ratio in an EmbeddedMediaPlayer if you want, or you can not set it and accept the default if that's what you want. There is a setAspectRatio method on MediaPlayer.

Performance will ALWAYS be much better in an EmbeddedMediaPlayer because VLC is natively playing your video (it never encounters the JVM), whereas with DirectMediaPlayer your video is being rendered by your JVM.

You can get acceptable performance, but usually with high CPU cost, for the DirectMediaPlayer. I've created full-screen HD video players on not high-end CPU/GPU before, but of course you are limited by hardware.

There is an experimental branch of vlcj that should increase the performance of DirectMediaPlayer by removing an entire frame copy per frame of video. Maybe that can help you https://github.com/caprica/vlcj/tree/experimental

**Comment by cassiohoffmann** [comment]
thanks for the quick response!

the short question would be:
how to use the EmbeddedMediaPlayerComponent assuming that I need the video to be stretched out independent if it loses the proportions

**Comment by caprica** [comment]
Use mediaPlayer.setAspectRatio to set the video size to the aspect ratio of your screen.

**Comment by cassiohoffmann** [comment]
Hello, I need to stretch the video without displaying the bars, but I do not really need to stretch the video to the proportion of the window even though it is distorted. that is the requirement. I could not use the aspect ratio because I reproduce a sequence of videos and each one can have a proportion and they have to fit in the window without human intervention. for example if the window has 1478x720 or 1800x720, I need it to stretch to fill the entire visible area

**Comment by caprica** [comment]
1. Get the screen resolution.
2. Set the aspect ratio.

?

**Comment by caprica** [comment]
Or is it that you need it to be inside a window rather than full-screen?

**Comment by cassiohoffmann** [comment]
friend, I discovered the problem with your help. !!!
I was displaying the video in a jframe with the edges so it was not beating the proportions. when I removed the borders and title from the window, it magically worked.

grateful for the help
