### ISSUE TITLE
timeChanged fires too infrequently

### ISSUE THREAD

**Issue by burniejm** [caprica/vlcj#593]
Our project uses vlcj and works great. A new feature we added allows users to pause a video and overlay drawings at specific times. When the user plays the video and the time reaches the point where there is an overlay the player pauses and shows the overlay. Our issue is that the timeChanged event only seems to fire ~ every 300 ms causing overlays to be shown +/- ~200ms from where they should. Is there any way to get finer grained timeChanged events?

We are using 3.10.1

**Comment by acely** [comment]
The answer here is NO.
This is a vlc core problem, and vlc does not provide any way to change that. So this is not a vlcj issue.
I use vlcj in my subtitle making tool, so timing is more important for me, 300ms is way too inaccurate. So what I'v done is to use a Timer instance as the "playhead runner", when the player listener fires played event, let the timer do scheduleAtFixedRate() to update/refresh whatever you're controlling. And in this way you can set your own update frequency.
And when the player listener fires onpause event, you cancel the timer.

BUT, this method may cause unsync between your playhead and the real player time (for example, the player is buffering and your time still runs). So you may need to use timeChanged() to calibrate your playhead.

To conclude, vlc is not good at doing precise jobs this like this, so a lot of hacky things need to be done. But vlcj itself is a great thing.

**Comment by caprica** [comment]
Unfortunately, that analysis is correct.

**Comment by acely** [comment]
By the way, I'm doing some research on using mpv player (which performs much better than vlc in many aspects) with java, but my power is limited, wondering if caprica has intrest in this?

**Comment by caprica** [comment]
@acely 5+ years ago I indeed made a Java framework for mplayer, which mpv is based on, but at the time the API was much less useful than LibVLC. I don't know the current situation. I don't think I really have the capacity right now to take on another similar-sized project.

**Comment by acely** [comment]
@caprica Yeah, totally understand you. For men growing means more responsibility, and that we have to take. So less time for our interest or passion or ambition...
But still thank you for giving us vlcj, such a wonderful present. Which inspired me alot, helped me solved many problems, and gives me (and I believe many other developers as well) new opportunities to do creative things.

For now, many people(including myself) sadly find that videolan is more or less giving up vlc, only few bug fixes per year maybe. We think videolan may keep vlc as a pretty stable thing rather than making the best of it. So vlc may still live very long but it's not keeping up with the times.

Video industry is very revolutionary these years, and many changes are coming, more and more high resolution/framerate/bitrate videos are beyond the capability of vlc. Ps: vlc can't even play mp3 files smoothly(lots of clicking sound come from nowhere and takes forever to seek).

In comparison, mpv is now very active, and handles those "heavy" videos easily. It also has a complete manual (https://mpv.io/manual/stable/) and libmpv which are developer friendly.

As I mentioned, I'm developing a subtitling tool, and vlc brings me lots of trouble, I had to write a lot hacky codes. But in mpv, those troubles are simply not exist. Other than that, mpv provides more features than vlc, which gives developers more opportunities.

So I think mpv is the player of the times, and thus a framework between mpv to java is very in need indeed. I'm writing some basic codes todo that, and I'm passionate. If I worked out something useful and I will put it on github too.
