### ISSUE TITLE
Most Player parameters are completely ignored

### ISSUE THREAD

**Issue by roli8200** [caprica/vlcj#597]
Tried to play network streaming resource 
http://xxx.xxx.xxx.xxx:8080/steam/video.h264 for which the vlc player must be started with the parameter
--demux h264
Tried to add the parameters to the player opions in the way
{":demux=h264"}
{"demux=h264"}
{"--demux=h264"}
{"--demux","h264"}
none of the parameters has any effect. 
By instancing the video player factory with "-vvv" as factory options, I can see that the given parameter seems never arrive at the libvlc library

**Comment by caprica** [comment]
Hyperbole much?

You didn't say HOW you passed those options.

Some options must be passed via the `MediaPlayerFactory`. That is simply how LibVLC works and is not a limitation caused by vlcj.

These options are passed directly to LibVLC from vlcj, either via the native libvlc instance, or via the libvlc native media player instance.

If they're ignored as you allege, then it is not vlcj that is ignoring them. Most likely you're not passing them correctly.
