### ISSUE TITLE
DirectMediaPlayer wrong vertical resolutions

### ISSUE THREAD

**Issue by andre111** [caprica/vlcj#616]
DirectMediaPlayer seems to provide frames with slightly wrong (bigger) resolution.

A 1280x720 video that displays with the correct resolution in VLC.
When played with a DirectMediaPlayer it results in 1280x736. 
Smaller videos have smaller errors, but they seem to appear in pretty much any video.

There are no bars/borders visible in the wrong sized frames, so they appear to be slighty streched overal.

**Comment by caprica** [comment]
So le tme try and understand this report...

You are saying if you provide a BufferFormatCallback that requests 1280x720, when you actually get the buffer it is 1280x736?

The only thing that I can think of that even vaguely could related to this is that the buffer itself may be larger than that requested because for LibVLC the native video buffer must be aligned to a 32-byte boundary. That doesn't mean the extra bytes are used of course.

Anyway, it's not clear to me what's actually wrong here.

**Comment by andre111** [comment]
getBufferFormat actually gets called with the wrong size

**Comment by andre111** [comment]
After some more testing this seems more like a libvlc bug.
The behaviour actually changes a bit with every major release:
Version 2.1.5 seems to work correctly
Version 2.2.X seem to always report the wrong size (1280x736)
Version 3.0.X actually call getBufferFormat three times. Twice with the correct size and then finally with the wrong size again

**Comment by andre111** [comment]
This seems like a really ugly hacked together solution, but using this code with version 3.0.3 results in frames with the correct size and exactly matching the data produced by vlc version 2.1.5:

`		if (sourceWidth == lastWidth && sourceHeight!=lastHeight && System.currentTimeMillis() - lastTime < 250) {
			System.out.println("Overriding height from " + sourceHeight + " to " + lastHeight);
			sourceHeight = lastHeight;
		}
		lastWidth = sourceWidth;
		lastHeight = sourceHeight;
		lastTime = System.currentTimeMillis();`

**Comment by caprica** [comment]
For this type of solution can't you simply detect if the BufferFormat class was used/invoked before (e.g. using a counter or a flag) rather than messing about with timers that will potentially introduce a race?

You could provide some other method to "reset" your BufferFormat before you played new media and so on.

This wouldn't be nice either of course, but I really, really don't like timers.

**Comment by andre111** [comment]
That indeed seems a lot better.

I will leave it like that for now and just hope vlc fixes this soon. 
Altough chances seems low seeing this is a bug existing since Version 2.2.0

**Comment by caprica** [comment]
Leaving this issue open as a reminder to document this somewhere.

**Comment by caprica** [comment]
Best I can do here is add a comment to the Javadoc, as per d3902045fa525787f95c23cbf72863c690ce533c.

**Comment by caprica** [comment]
Just a foot-note to this issue for possible future reference...

I have seen the buffer format callback called multiple times as per the description in this issue - it seems that it gets called multiple times with different chroma formats. In the case of vlcj test applications RV32 is used and this the callback is called with this chroma value last.
