### ISSUE TITLE
The quest for stable video playback in Swing GUIs

### ISSUE THREAD

**Issue by stefan-reich** [caprica/vlcj#650]
It's not easy. In fact, there doesn't seem to be a solution so far.

JavaFX supports only very few video types.

VLCJ is great in theory - but it really does seem to crash (see #585). I'm seeing weird behavior and JVM crashes in my tests too (on Linux 64). Not sure if these can be remedied, I kind of lost faith in VLCJ right now.

Also, seeing as there haven't been any VLCJ releases since 2015...

JMF doesn't handle important formats (MP4).

Xuggler is worth a look, I'm looking into it now. Edit: It's outdated, forget it...

[GStreamer-Java](https://github.com/gstreamer-java/gst1-java-examples/blob/master/src/main/java/org/freedesktop/gstreamer/examples/PlayBinVideoPlayer.java) does work in an initial test on 64-bit Linux.

So maybe one wants to use a different tool for each platform. GStreamer-Java for Linux, VLCJ for Windows... and something unknown for Mac (VLCJ needs a special mode there).

Anything else?

**Comment by caprica** [comment]
There have not been any VLCJ releases recently because its API and implementation is stable, and LibVLC's API has also been stable for a long time. Equally VLC has a very long time between releases, and often not much changes in LibVLC. So vlcj is not the type of project that churns out frequent new releases just for the sake of it.

Interfacing with native code is always difficult and prone to crashes. Put some effort in and investigate your crashses and maybe they can be addressed.

I exclusively use 64-bit Linux for my own vlcj projects and I don't encounter problems. The general advice, on all platforms, is to use a single native media player per JVM, and to use the native playlist rather than your own. The most common mistake that developers make is to call back into LibVLC from an event handler - this is generally forbidden and can often lead to crashes.

If you have a particular issue, post it, but right now there's not much that can be usefully addressed.

**Comment by stefan-reich** [comment]
OK, that does give me hope. Thanks for your quick answer.

I'm beginning to see the problem - I have two versions of JNA in my class path (VLCJ/OSHI). Thanks

**Comment by caprica** [comment]
Well, I'm not saying vlcj is a perfect solution to this problem. But people using vlcj and LibVLC must learn to work within the limits of LibVLC. LibVLC not being re-entrant from event handlers in one such critical limit.

Most people (and I'm talking here of people experienced in Java programming but not necessarily experienced in systems or native programming) expect, reasonably I suppose, that say in an event handler they can write whatever code they want. But these event handlers are running on a native thread, and whatever you do in that event handler you must be careful to not call back into LibVLC until that native thread has finished.

So the prime example, you get an event telling you the current media has ended, what do you do - you immediately call mediaPlayer.play(...) to start the next media in your playlist. But you have inadvertently called back into LibVLC from a native event handler by doing that. This might work 99% of the time, but it might crash that one time...

So, most people bodge a solution by offloading that event handling to a separate Java thread, and this will work a lot of the time, and if not, people tend to stick a Thread.sleep(1) or so in there. This gives the native event handler time to finish before you call back in. Now this isn't a great solution, it's still subject to a race, but it works reliably enough for the vast majority of people.

How do you stop this?

Well, most applications should either use the native playlist which will just play the multiple videos one after the other, or play new media in response to something like a button press. In neither of these cases are you calling back into LibVLC from a native thread. So this will work.

So, most of the crashes I hear about are related to situations like this, i.e. where people are pushing (exceeding in fact) the limits of what can be done with LibVLC/vlcj.

And to be fair, even from those naive developers, considering the consistent number of monthly downloads I see for vlcj, I would expect to hear a LOT more complaints if significant numbers of people are having problems.
