### ISSUE TITLE
Video output stops updating when paused

### ISSUE THREAD

**Issue by raul3d** [caprica/vlcj#658]
When seeking through a media file that is paused, after some time the video output freezes and stops updating. Briefly playing and pausing again temporary resolves the issue.

To reproduce:
- Happens with the test player (e.g. current state of vlc-player-master)
https://github.com/caprica/vlcj-player
- Seems to happen with all media files (e.g. the big buck bunny trailer, I tried with "Full HD VP9" version)
https://commons.wikimedia.org/wiki/File:Big_Buck_Bunny_Trailer_1080p.ogv
- Open the downloaded trailer, pause the movie and keep seeking through the movie. After a few seconds (5-10), the video output should stop refreshing.

This seems to be independent of the used MediaPlayer: It happens with DefaultEmbeddedMediaPlayer (e.g. vlc-player), but also happens with DefaultDirectMediaPlayer. All events still appear to be fired correctly (time/position changed, buffering up to 100%); however, taking a snapshot once the video output froze, will take a snapshot of the frozen moment. Since video output for the EmbeddedMediaPlayer is handled by libvlc it seems to be an issue there, but strangely this does not happen in the standalone VLC player.

Could there be any buffers or logs that are running full?

I used these versions (but this also happened with previous VLC, VLCJ and JDK versions)
vlcj: 3.10.1 (latest)
vlc: 3.0.4 (latest)
JDK 8 u191 x84
Windows 8.1 x64

**Comment by caprica** [comment]
Well, does this happen with your own code in your own application?

With vlcj-player this is seemingly happening when *continually* dragging the video slider. When just jumping around with single clicks on the seekbar, it works just fine. The seeking implementation in vlcj-player is just an example to get you started and might not be the best. IIRC that code was actually a contribution by a third party, it has complexities in there dealing with native threads, the UI thread, and event bus threads. There could plausibly be races in there somewhere.

**Comment by caprica** [comment]
This is seemingly a vlcj-player issue, not a vlcj core issue, so I'll close it here.

**Comment by caprica** [comment]
I did some testing on this.

It seems that this issue may actually be inside VLC/LibVLC since my testing showed that mediaPlayer.setPosition(...) was always correctly being called with the new position when dragging that position slider around. It seems that VLC/LibVLC just eventually stops sending frames for the new position when the media is paused - presumably because it is no longer decoding frames when paused.

In any event, this can not be fixed in vlcj or vlcj-player.

**Comment by raul3d** [comment]
Thanks for taking another look at this, I though you already gave up on it.

After the busy new years time, I had some time to also check this again. These are my findings:
- Looking at VLC's own code, seeking also just calls libvlc_media_player_set_position without any synchronisation. However, the issue does not seem to happen there.
- The "buffering" events in vlcj are still fired with changing values, so LibVLC is still doing something.
- Waiting for buffering = 100% before changing the position again does not resolve the issue. So what ever race-codition is happening, it is not over at this time.

I am puzzled what could case this behaviour or what to try next.

**Comment by caprica** [comment]
It's not that I give up on issues like this, it's just that experience tells me things like this are almost certainly never anything that can be fixed in vlcj.

Anyway, it's interesting that the buffering events still occur, but I always come back to this: vlcj is not responsible for playing your video, vlcj never paints any video frames (well, ignoring the "direct" rendering stuff for now), it is VLC/LibVLC that is painting the video frames natively. So if the embedded Canvas does not update with a new frame while paused, it can only be because VLC/LibVLC didn't decode/render any new video frame into that Canvas.

Just to be even more clear, vlcj does not even ask LibVLC for the next frame, vlcj is completely passive while VLC/LibVLC renders the video.

**Comment by caprica** [comment]
Obviously I'll reopen the issue if there's something to be done in vlcj, but I honestly doubt it.
