### ISSUE TITLE
Get video bounds within the video surface canvas

### ISSUE THREAD

**Issue by bjorndarri** [caprica/vlcj#852]
Is there a way to get the bounds of the actual video within the video surface?

I was hoping to find something along the lines of MediaPlayerComponent.getVideoBounds() returning a Rectangle, which would fall within the video surface.

I'm working on a video annotation tool and would like to allow the user to click on an object in the video and register its location, but without the video bounds that seems impossible.

**Comment by acely** [comment]
From my point of view you don't have to ask vlcj for the bounds.

First you know the location and size of your video surface, then you can use the media info api provided by vlcj (or use ffprobe if you like) to get the display size of your video.

Then it's just some simple math, because vlc fits the video into the video surface by default.

For more info about vlcj info api, see http://capricasoftware.co.uk/projects/vlcj-4/tutorials/media-info

**Comment by acely** [comment]
You should also notice that for some video, the pixels are NOT square, so you should use "display size" rather than "pixel size".

**Comment by caprica** [comment]
@acely is completely right, you know the video surface component size, the video size, and the SAR so you can apply a formula and work out the on-screen extent of the actual used video surface (leaving aside any black bars intrinsic to the video). You may also need to take into account the display-aspect-ratio, I'm not sure.

The whole thing is slightly tricky because the video size and the SAR are not known immediately when the media starts playing - you can try waiting for a mediaPlayerReadyEvent, or keep polling track information until it returns something valid.

The other tricky thing is that there is no concrete link between the currently selected video track and the unique track identifiers provided in track information - if you have single-track video you could of course just assume they relate.

Of course as was suggested above you don't need to use the LibVLC track information, you can extract the video track info by some other means ahead of time.

The formula for handling non-square pixels is a little tricksy if you have the same apathy for maths that I do.

If it would be trivial for vlcj to provide an API to get that rectangle, then I would have done it, but as you can see it has some difficulties that are best left to client applications to deal with IMO.

**Comment by bjorndarri** [comment]
That was actually the method I started implementing (and will probably end up using), but kept seeing black bars of varying width/height (a few pixels) appearing around the video when resizing the containing window. So it looks like the video doesn't fit "pixel perfect" within the canvas and that would reduce the precision somewhat when doing the required calculations. I'll look into this further on Monday when I'm back at work.

**Comment by caprica** [comment]
I did some similar work to this a month or so ago trying to get DVD to render properly with the video callbacks (DVD uses non-square pixels). I am pretty sure I was able to get pixel-perfect resizing with no "wrong" black bars (I overlaid the VLC app on top of my app and the resize behaviour was identical). The only black bars I saw were those intrinsic to the video itself (which is OK of course, because those clicks are actually "in" the video).

Unfortunately that code is not available in vlcj, sorry. But it should be possible to get a proper bounding box with proper application of the formulae and proper scaling/rounding.

**Comment by bjorndarri** [comment]
Thanks for the help @acely and @caprica, looks like I'll be able to solve this using your method. I'm not well versed in github etiquette, so I don't really know if I should close this issue myself, so feel free to close it.

**Comment by caprica** [comment]
No worries, I will close it. Glad you got enough for a way forward.

Just to put a footnote on this issue, I hope you can see why it's not really appropriate to build this API into vlcj (at least at the moment) - any solution for this is an uncerctain compromise and those sorts of things are best left to client applications IMO.
