### ISSUE TITLE
Snapshot directory seems to be ignored

### ISSUE THREAD

**Issue by mariankh1** [caprica/vlcj#863]
Hi, I am using an EmbeddedMediaPlayer.
Although I call embeddedMediaPlayer.setSnapshotDirectory("src/"); this is ignored.
when I call mediaPlayer.getSnapshot(); it shows on the frame that this is saved somewhere in /temp/jvlc-player... 

1) is there a way to set this directory?
2) is there a way to not show the text with the location of the screenshot on the screen/ or change its font size? 

Thanks.

**Comment by caprica** [comment]
setSnapshotDirectory works for me.

If you're using the save() method that takes a File, then the snapshot directory is ignored, since a File is assumed to have its own inherent path.

For your second question there is no specific API to do any of that, but you can do this:

        MediaPlayerFactory factory = new MediaPlayerFactory(new String[] {"--no-osd"});

Note that specifying "no on-screen display" may have other effects that you might not want.

And if you don't want the little thumbnail preview window:

        MediaPlayerFactory factory = new MediaPlayerFactory(new String[] {"--no-osd", "--no-snapshot-preview"});

**Comment by mariankh1** [comment]
Thank you! this works!
