### ISSUE TITLE
BufferFormatCallback uses incorrect sourceHeight for 1080p videos

### ISSUE THREAD

**Issue by ChrRubin** [caprica/vlcj#867]
As stated in #616, #752 as well as BufferFormatCallback's Javadoc, VLC invokes the callback multiple times with different values for the sourceHeight parameter. My current workaround is to ignore subsequent sourceHeight changes, which works fine on 1280x720 videos.

However, for 1920x1080 videos, it seems that VLC provides the wrong sourceHeight right from the start, giving 1920x1088 twice and then 1920x1090.

**Comment by caprica** [comment]
I'm not sure what you expect of vlcj in this case.

Vlcj presents you with what VLC sends.

And are you sure the size is actually incorrect? Because there is nothing that says the buffer format must match the display pixel size, it depends on the chroma format.

As explained in the other issues VLC is negotiating a compatible buffer format so you should always be prepared for that callback to be invoked multiple times and use whatever the last callback tells you.

**Comment by ChrRubin** [comment]
To be fair I don't really understand the difference between buffer format and display size, I'm guessing it's something to do with memory optimization. When playing in normal VLC the video resolution is shown as 1920x1080 and buffer dimensions is shown as 1920x1090.

Coincidentally is there any way to get the video's display size when using direct rendering? I'm following the examples from vlcj-javafx which uses the buffer format's size for displaying the video instead of the display size.

**Comment by caprica** [comment]
Some buffer formats will have to be aligned and or padded to 16 or 32 byte boundaries for example. So a display size or media size of 800x599 wouldn't work.

For the video size when direct rendering you can use the track info API, but it isn't always reliable trying to link track IDs. There's no problem if your media only has none video track of course.

**Comment by ChrRubin** [comment]
Thanks for the explanation. I'll try getting the display size before rendering the video.

Thanks for your help.

**Comment by caprica** [comment]
In summary, I think the callback is working correctly and the values are not "incorrect" - they may not be exactly as you'd expect, but they're not wrong either.
