### ISSUE TITLE
Window overlay can't refresh graphics after every loops

### ISSUE THREAD

**Issue by sci-ripper** [caprica/vlcj#905]
I'm trying to draw over a vlcj (java binding of the VLC library) panel so that I can play a video and draw over it. And I have encounter some issues. Here is the full base code:

**Code-listing 1: AppOverlay.java**

```
package app;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Window;
import java.awt.image.BufferedImage;
import java.io.IOException;

import javax.imageio.ImageIO;

import com.sun.jna.platform.WindowUtils;

@SuppressWarnings("serial")
public class AppOverlay extends Window implements Runnable {

    private final boolean isRunning;
    private final int fps;
    private BufferedImage graphics;
    private BufferedImage img;
    private int x, y;
    private boolean ltr;

    public AppOverlay(Window owner) throws HeadlessException {
        super(owner, WindowUtils.getAlphaCompatibleGraphicsConfiguration());
        setBackground(new Color(0,0,0,0));

        graphics    = new BufferedImage(1280,800, BufferedImage.TYPE_INT_ARGB);
        isRunning   = true;
        img         = null;
        ltr         = true;
        fps         = 60;
        x           = 0;
        y           = 0;
    }

    @Override
    public void run(){
        while(isRunning){

            try{
                Thread.sleep(1000/fps);
            } catch(InterruptedException e){
                e.printStackTrace();
            }

            if(ltr) {
                if(x < 1280) x++;
                else ltr = false;
            } else {
                if(x < 0) ltr = true;
                else x--;
            }

            repaint();
        }
    }

    public void createAndShowGUI() {
        setVisible(true);

        Thread thread = new Thread(this);
        thread.start();

        String path = "Drive:\\path\\to\\image.png";
        try {
            img = ImageIO.read(new java.io.FileInputStream(path));
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    @Override
    public void paint(Graphics g) {
        Graphics2D g2d = (Graphics2D)g;
        Graphics2D gfx = graphics.createGraphics();
        gfx.setColor(new Color(255,255,255,0));
        gfx.clearRect(0, 0, 1280, 800);
        if(img != null) gfx.drawImage(img, x, y, null);
        gfx.dispose();
        g2d.drawImage(graphics, 0, 0, null);
    }
}
```
**Code-listing 2: AppPlayer.java**

```
package app;

import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

@SuppressWarnings("serial")
public class AppPlayer extends EmbeddedMediaPlayerComponent {

}
```
**Code-listing 3: AppFrame.java**

```
package app;

import java.awt.Dimension;

import javax.swing.JFrame;

@SuppressWarnings("serial")
public class AppFrame extends JFrame {

    private AppPlayer appPlayer;
    private AppOverlay overlay;

    public AppFrame(){
        super();
    }

    public void createAndShowGUI() {

        appPlayer = new AppPlayer();
        appPlayer.setPreferredSize(new Dimension(1280,800));
        getContentPane().add(appPlayer);

        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setTitle("App");
        setVisible(true);
        pack();

        overlay = new AppOverlay(this);
        appPlayer.mediaPlayer().overlay().set(overlay);
        appPlayer.mediaPlayer().overlay().enable(true);
        overlay.createAndShowGUI();
    }
}
```
**Code-listing 4: Main.java**

```
package main;

import javax.swing.SwingUtilities;

import app.AppFrame;

public class Main {

    public static void main(String[] args) {
        final AppFrame app = new AppFrame();
        SwingUtilities.invokeLater( new Runnable() {
            @Override
            public void run() {
                app.createAndShowGUI();
            }
        });
    }

}
```
with that and the vlcj-4 library you should be able to test my code yourself. My issue is that the Overlay (AppOverlay class that extends the Window class) doesn't display or refresh the animation unless I deselect the window (I click on another window or on the desktop or the OS toolbar) so that the window (application) is inactive then select the window (the application) again. It will only load one frame and that's it. I have to deselect and reselect the window again for it to load another frame (this is only the case for the Overlay i.e. if I play a video in the AppPlayer class the video will be playing just fine.

What I want is to be able to draw some animated graphics on the overlay. I know that with the JPanel class there is the paintComponent() method but the Window class doesn't have that method (only the paint() and repaint() methods are available).

What should I do to fix this?

**Comment by caprica** [comment]
I know you're using vlcj's overlay, but this issue is nothing to do with vlcj really.

You should first get your custom rendering working in a project without vlcj, just get your rendering working without worrying about the video.

That will be much easier than dealing with vlcj at the same time.

To actually get your rendering working it's just a question of using Java2D appropriately, maybe an animation timer and so on.

And by the way, rendering into a Window via paint() should be just fine, but if you want, nothing prevents you from adding a JPanel or something to your window and rendering into that instead. You will have to deal with transparency, but it should work.

**Comment by sci-ripper** [comment]
I'm sorry I'm asking for support here when it's not really an issue. The fact is that I asked on stackoverflow and no one has the answer. And since you created VLCJ I though you were the best person to ask this question. Someone on stackoverflow suggested I should solve this by enabling and disabling the overlay with some kind of a timer but the problem is that the graphics looks like they are blinking.

The same happens when I do what you first suggested (drawing directly on a Window first without using VLCJ) but when I try what you suggested after (drawing on a JPanel) the animation are drawn smoothly. So I tried it with VLCJ and the animation are drawn flawlessly and smoothly. The only issue is that as far as I know there is no way to make a JPanel transparent as there is no way to set the GraphicsConfiguration like you did on your tutorial for the Window class (overlay tutorial).

**Comment by caprica** [comment]
There's no reason to be sorry about it.
But if your problem isn't to do specifically with vlcj you might have better luck in some other forum to get the help you need.

For overlays in vlcj, the best results are really obtained by using the "callback" video surface (this used to be call the "direct" media player.

This will give you a Java2D context to render directly into the video.

This works in either JavaFX or Swing.

The downside is that you have to render the video rather than vlc render it, so the performance is likely not as good.

However, the overlay result is much nicer this way.

If you are interested in that, have a look at the vlcj-javafx project and/or look in the vlcj test examples for the callback media player component and/or callback video surface.
