### ISSUE TITLE
How to create a 5 band equalizer?

### ISSUE THREAD

**Issue by linux-man** [caprica/vlcj#910]
I can create a n band equalizer using the constructor Equalizer(int bandCount),
but I can't assign it to a mediaPlayer. Only 10 bands are supported?

**Comment by caprica** [comment]
You're not supposed to create instances of the Equalizer yourself, you're supposed to go via the MediaPlayerFactory.

Ideally that constructor you're using would have been private, but that's not possible because I wanted to keep the Equalizer class and the MediaPlayerFactory class in their own separate packages.

What happens in the factory is that internally it uses the native LibVLC library to query the available equalizer bands, and currently this is 10 fixed bands at specific frequencies.

**Comment by linux-man** [comment]
Thank you for the clarification and a Happy New Year!
