### ISSUE TITLE
setTime not work

### ISSUE THREAD

**Issue by XDIYIBEIZI-XH** [caprica/vlcj#975]
As the timeline slides, I call the setTime() method. but the ImageView no follow display.

**Comment by caprica** [comment]
setTime does work.

The vlcj-player and vlcj-javafx-demo projects show a working slider for the timeline.

**Comment by XDIYIBEIZI-XH** [comment]
the slow change is ok, but at fast change the imageview sometimes no follow display, imageview will pause at one point.

**Comment by caprica** [comment]
From what I can remember, this sometimes happens when using VLC 3.x. Fast seeking is much better with VLC 4.x, but VLC 4.x might still be quite a long way from being released.

The point is there is no problem in vlcj here.

You could try throttling your setTime updates, but even that might not work.
