### ISSUE TITLE
High color depth support

### ISSUE THREAD

**Issue by andrewringler** [caprica/vlcj#981]
I am working with [Apple ProRes](https://en.wikipedia.org/wiki/Apple_ProRes) files 422HQ and 4444 which have color depths of 10-bits per channel (422) and 12-bits per channel (and 16-bits for alpha) for the 4444. I am currently using the RV32BufferFormat which I assume means I am losing some color information (since it is 8-bits per channel).

Are there any `BufferFormats` that are currently supported by `vlcj` that would preserve this color information?

I do see that v4 will support RGBA64, but I was wondering if there were any current ways of getting this in the v3 branch? It doesn't have to be an RGB BufferFormat.

**Comment by caprica** [comment]
You could of course make your own BufferFormat class if you found something that worked, but I have no idea really on what specifically would be needed.

Last time I looked into this, RV32 was the only thing that could be used with a BufferedImage - other formats kinda worked but with wrong colours or different scan widths or whatever. Perhaps it's possible, and necessary, to implement your own colour model as well, but I don't know.

If you only want to access the buffer rather than render it via BufferedImage, then IIRC you can provide the entire buffer format yourself, including width, height, planes, plane width and so on.

If VLC can play your video, you can get the buffer contents with vlcj, but whether you can render that image in Java as well, it's beyond anything I've ever done with vlcj.

**Comment by andrewringler** [comment]
Thanks! I'll post here if I have any working code examples to share.

**Comment by caprica** [comment]
Do you actually need to _render_ the video in Java?

Presumably also VLC plays your video as you expect?

**Comment by andrewringler** [comment]
I don't need to render the video to the screen. I am just performing some processing on each frame of the video (https://github.com/andrewringler/video-2-slit-scan).

**Comment by caprica** [comment]
Interesting Q&A here: https://apple.stackexchange.com/a/221198

> Just to be clear, ProRes was never intended as a playback format. ProRes was designed as an intermediate codec for use during video recording and editing, and was a replacement for Apple Intermediate Codec. As a result, it was never intended to be used as a "playback" format. That's why you could only play it back with QuickTime or editing software.

**Comment by caprica** [comment]
So I think you should be able to write a custom BufferFormat and specify each of the planes individually. Assuming VLC can play it.

**Comment by caprica** [comment]
You need to know pixel colour format ("chroma", in the API), width, height, pitch-size for each plane, and the number of planes. The pitch size does not need to be the same for each plane.

But that's the limit of what I can tell you, I never used any buffer format other than RV32 myself.

**Comment by andrewringler** [comment]
Yes, VLC is able to play it, and the default vlcj BufferFormat RV32, does convert my 16-bit ProRes videos into 8-bit RGB Buffers.

**Comment by andrewringler** [comment]
OK. Thanks Mark. I'll experiment a bit

**Comment by caprica** [comment]
Grepping VLC sources for 422 yields this:

```
    B(VLC_CODEC_I422, "Planar 4:2:2 YUV"),
        A("I422"),
    B(VLC_CODEC_J422, "Planar 4:2:2 YUV full scale"),
        A("J422"),
    B(VLC_CODEC_YUV422A, "Planar YUV 4:2:2 Y:U:V:A"),
        A("Y422"),
        A("V422"),
    B(VLC_CODEC_I422_9L, "Planar 4:2:2 YUV 9-bit LE"),
    B(VLC_CODEC_I422_9B, "Planar 4:2:2 YUV 9-bit BE"),
    B(VLC_CODEC_I422_10L, "Planar 4:2:2 YUV 10-bit LE"),
    B(VLC_CODEC_I422_10B, "Planar 4:2:2 YUV 10-bit BE"),
    B(VLC_CODEC_I422_12L, "Planar 4:2:2 YUV 12-bit LE"),
    B(VLC_CODEC_I422_12B, "Planar 4:2:2 YUV 12-bit BE"),
    B(VLC_CODEC_VDPAU_VIDEO_422, "4:2:2 VDPAU opaque"),
```

`/src/misc/fourcc_list.h` - this is also where RV32 is defined.
